site_name: Study of Philippians
theme: material
markdown_extensions:
  - admonition
extra_css: 
  - css/custom.css
use_directory_urls: false
nav:
  - Background Information: 00-background-info.md
  - 1 - Greetings and Prayer (1:1-11): 01-greeting.md
  - 2 - Paul's Imprisonment (1:12-26): 02-imprisonment.md
  - 3 - Live a Life worthy of the Gospel (1:27-2:18):
    - 3-1 Unity by humility (1:27-2:1-5): 03-01-unity-humility.md
    - 3-2 Jesus, the ultimate example of humility. (2:6-11): 03-02-jesus-humility.md
    - 3-3 Exhortation (2:12-18): 03-03-exhortation.md
  - 4 - Examples of Timothy and Ephaphroditus (2:19-30): 04-examples.md
  - 5 - Paul's Example (3:1-4:1): 
    - 5-1 Pressing on to the Goal (3:1-16): 05-01-press-goal.md
    - 5-2 Imitate their example. (3:17-4:1): 05-02-imitate.md 
  - 6 - Exhortations (4:2-9): 06-exhortations.md
  - 7 - God's provision and Paul's Contentment (4:10-23): 07-provision-contentment.md